//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroERP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MicroERPEntities : DbContext
    {
        public MicroERPEntities()
            : base("name=MicroERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeViolationInfo> EmployeeViolationInfo { get; set; }
        public virtual DbSet<FundsGoodsInfo> FundsGoodsInfo { get; set; }
        public virtual DbSet<FundsSalaryInfo> FundsSalaryInfo { get; set; }
        public virtual DbSet<GoodsConfirmInfo> GoodsConfirmInfo { get; set; }
        public virtual DbSet<GoodsOrderInfo> GoodsOrderInfo { get; set; }
        public virtual DbSet<GoodsRejectedOrderInfo> GoodsRejectedOrderInfo { get; set; }
        public virtual DbSet<GoodsResourceInfo> GoodsResourceInfo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TotalAssetsInfo> TotalAssetsInfo { get; set; }
        public virtual DbSet<UserSelfInfo> UserSelfInfo { get; set; }
        public virtual DbSet<UserUpdateInfo> UserUpdateInfo { get; set; }
        public virtual DbSet<EmployeeResource> EmployeeResource { get; set; }
        public virtual DbSet<EmployeeSalary> EmployeeSalary { get; set; }
        public virtual DbSet<GoodsApplyOrder> GoodsApplyOrder { get; set; }
        public virtual DbSet<GoodsConfirm> GoodsConfirm { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<EmployeeView> EmployeeView { get; set; }
        public virtual DbSet<UserSelf> UserSelf { get; set; }
    }
}
