//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeViolationInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeViolationInfo()
        {
            this.FundsSalaryInfo = new HashSet<FundsSalaryInfo>();
        }
    
        public int RecordID { get; set; }
        public string ViolateFor { get; set; }
        public decimal FundsPunish { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    
        public virtual UserSelfInfo UserSelfInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundsSalaryInfo> FundsSalaryInfo { get; set; }
    }
}
