//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeView
    {
        public int 员工编号 { get; set; }
        public string 姓名 { get; set; }
        public string 所属部门 { get; set; }
        public string 职位 { get; set; }
        public decimal 薪资 { get; set; }
        public string 在职状态 { get; set; }
        public Nullable<System.DateTime> 入职时间 { get; set; }
    }
}
