//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundsGoodsInfo
    {
        public int FundsForGoodsID { get; set; }
        public string FundsState { get; set; }
        public decimal FundsUpdate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string FundsNote { get; set; }
    
        public virtual UserSelfInfo UserSelfInfo { get; set; }
        public virtual GoodsOrderInfo GoodsOrderInfo { get; set; }
    }
}
