//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsResourceInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsResourceInfo()
        {
            this.GoodsOrderInfo = new HashSet<GoodsOrderInfo>();
        }
    
        public int GoodsID { get; set; }
        public string GoodsName { get; set; }
        public long GoodsQuantity { get; set; }
        public string GoodsCountingUnit { get; set; }
        public int GoodsUnitPrice { get; set; }
        public string GoodsFrom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsOrderInfo> GoodsOrderInfo { get; set; }
    }
}
