//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsRejectedOrderInfo
    {
        public int RejectID { get; set; }
        public int RejectOrderID { get; set; }
        public int RejectBy { get; set; }
        public string RejectState { get; set; }
        public int RejectUserID { get; set; }
        public string RejectNote { get; set; }
    
        public virtual GoodsConfirmInfo GoodsConfirmInfo { get; set; }
        public virtual GoodsOrderInfo GoodsOrderInfo { get; set; }
        public virtual UserSelfInfo UserSelfInfo { get; set; }
    }
}
