//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsConfirmInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsConfirmInfo()
        {
            this.GoodsOrderInfo1 = new HashSet<GoodsOrderInfo>();
            this.GoodsRejectedOrderInfo = new HashSet<GoodsRejectedOrderInfo>();
        }
    
        public int ConfirmID { get; set; }
        public int ConfirmOrderID { get; set; }
        public int ConfirmUserID { get; set; }
        public string ConfirmType { get; set; }
        public string ConfirmNote { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
    
        public virtual GoodsOrderInfo GoodsOrderInfo { get; set; }
        public virtual UserSelfInfo UserSelfInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsOrderInfo> GoodsOrderInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsRejectedOrderInfo> GoodsRejectedOrderInfo { get; set; }
    }
}
