//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserResourceInfo
    {
        public int UserID { get; set; }
        public string UserDepartment { get; set; }
        public string UserPosition { get; set; }
        public decimal UserSalary { get; set; }
        public string UserStatus { get; set; }
    
        public virtual UserSelfInfo UserSelfInfo { get; set; }
    }
}
