//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSelfInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSelfInfo()
        {
            this.EmployeeViolationInfo = new HashSet<EmployeeViolationInfo>();
            this.FundsGoodsInfo = new HashSet<FundsGoodsInfo>();
            this.FundsSalaryInfo = new HashSet<FundsSalaryInfo>();
            this.GoodsConfirmInfo = new HashSet<GoodsConfirmInfo>();
            this.GoodsOrderInfo = new HashSet<GoodsOrderInfo>();
            this.GoodsRejectedOrderInfo = new HashSet<GoodsRejectedOrderInfo>();
            this.UserLoginInfo = new HashSet<UserLoginInfo>();
            this.UserResourceInfo = new HashSet<UserResourceInfo>();
            this.UserUpdateInfo = new HashSet<UserUpdateInfo>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserAddress { get; set; }
        public string SelfIntroduction { get; set; }
        public string ProfilePictureAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeViolationInfo> EmployeeViolationInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundsGoodsInfo> FundsGoodsInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundsSalaryInfo> FundsSalaryInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsConfirmInfo> GoodsConfirmInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsOrderInfo> GoodsOrderInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsRejectedOrderInfo> GoodsRejectedOrderInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLoginInfo> UserLoginInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserResourceInfo> UserResourceInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserUpdateInfo> UserUpdateInfo { get; set; }
    }
}
