//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserUpdateInfo
    {
        public int UpdateID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateType { get; set; }
        public string UpdateFrom { get; set; }
        public string UpdateInto { get; set; }
        public string UpdateInformation { get; set; }
    
        public virtual UserSelfInfo UserSelfInfo { get; set; }
    }
}
