//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUserSelf
    {
        public int 员工编号 { get; set; }
        public string 姓名 { get; set; }
        public string 手机号 { get; set; }
        public string 联系地址 { get; set; }
        public string 自我介绍 { get; set; }
        public string 头像链接 { get; set; }
        public string 电子邮箱 { get; set; }
        public string 密码 { get; set; }
    }
}
