//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeSalary
    {
        public int 用户编号 { get; set; }
        public int 工资单编号 { get; set; }
        public int 违规记录编号 { get; set; }
        public string 姓名 { get; set; }
        public string 所属部门 { get; set; }
        public string 职位 { get; set; }
        public decimal 预期薪资 { get; set; }
        public decimal 基本工资 { get; set; }
        public decimal 绩效奖金 { get; set; }
        public decimal 违规罚款 { get; set; }
        public decimal 实发工资 { get; set; }
        public Nullable<System.DateTime> 发薪时间 { get; set; }
    }
}
